.TH RESTOOL 1 "June 20, 2014"
.SH NAME
restool \- Layerscape Resource Management Tool
.SH SYNOPSIS
\fBrestool\fP [global-options]
.br
\fBrestool\fP -h
.br
\fBrestool\fP -v
.br
\fBrestool\fP -m
.br
\fBrestool\fP [global-options] [obj-type] [command] [obj-name] [ARGS ...]
.br
\fBrestool\fP -s [obj-type] [command] [obj-name] [ARGS ...]
.br
\fBrestool\fP -d [obj-type] [command] [obj-name] [ARGS ...]
.SH DESCRIPTION
\fBrestool\fP can be used to do dynamic management of Management Complex
resources. Key resource management operations include:
.br
1) listing containers and their contents
.br
2) creating/destroying containers/objects
.br
3) retrieve info from containers/objects
.br
4) establishing connections between objects
.SH GLOBAL-OPTION
-v, -m, -h options can only be used individually
.TP 8
-v, --version
Displays tool version info
.TP
-m, --mc-version
Displays mc firmware version.
.TP
-h, -?, --help
Displays general help info
.TP
-d, --debug
Print out DEBUG info
.br
--debug option must be used together with an object
.br
e.g. restool --debug dpni info dpni.11
.TP
-s, --script
Print newly-created object name only instead of whole sentence
.br
e.g. restool -s dpseci create
.br
     dpseci.0
.PP
.SH OBJ-TYPE
Valid obj-type values are:
.br
dprc|dpni|dpio|dpsw|dpbp|dpci|dpcon|dpseci|dpdmux|dpmcp|dpmac|dpdcei|dpaiop
.SH COMMAND
Use the 'restool dp* help' command to see detailed usage info for an object.
The following commands are valid for all object types.
.br
.in 12
help
.br
info
.br
create
.br
destroy
.SH OBJ-NAME
This is the instance of each object type. e.g. dprc.1 is an instance of dprc obj-type
.SH HELP-MESSAGE
There are 3 levels of help, from top to bottom
.TP 8
global
restool --help
.TP
object
restool dp* help
.br
tells you all the commands this object support.
.br
e.g. restool dprc help
.TP
object-command
restool dp* [command] --help
.br
tells you how to use this [command]
.br
e.g. restool dprc create --help
.PP
.SH GIT-REPO
http://sw-stash.freescale.net/projects/DPAA2/repos/restool
.SH AUTHOR
Current Maintainer/Contributor is Lijun Pan
.br
Initial Version drafted by Jose German Rivera
.SH COPYRIGHT
BSD-3-CLAUSE & EULA
